# Site settings
name: name
email: email
url: url
description: "A blog"
author: "FoxHustle"
title: "ItFails"
permalink: pretty
baseurl: /

# social
github:
  username: username

twitter:
  username: username
