# Site settings
name: ITFails
email: email
url: itfails.news
description: "A blog"
author: "FoxHustle"
title: "ITFails"
permalink: pretty
baseurl: /

# social
github:
  username: username

twitter:
  username: username
