# Site settings
name: ITFails
email: email
url: "https://itfails.news"
description: "A blog"
author: "FoxHustle"
title: "ITFails"
permalink: pretty
paginate: 5
baseurl: /
plugins:
  - jekyll-news-sitemap
