# Site settings
name: ITFails
email: email
url: "https://itfails.news"
description: "A blog"
author: "FoxHustle"
title: "ITFails"
permalink: pretty
baseurl: /
plugins:
  - jekyll-sitemap
  
# social
github:
  username: username

twitter:
  username: username
