# Site settings
name: ITFails
email: email
url: "https://itfails.news"
description: "A blog"
author: "FoxHustle"
title: "ITFails"
permalink: pretty
baseurl: /
plugins:
  - jekyll-news-sitemap
  - jekyll-analytics
  
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: G-54TL2L5LLG          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
